### ISSUE TITLE
第2話 iOSDC2016振り返り（仮名）

### ISSUE THREAD

**Issue by yimajo** [stargzr/radio#1]
# おおざっぱな主旨

- iOSDC2016の振り返りをしてみよう（前半）
- 次はああしたいこうしたいを話してみよう（後半）

2回に分けて1回分を短く、聴きやすいものにしてみよう

# メンバー

- 長谷川さん

# 場所

- Tech Lab PAAK （6Fの受付でimajoとの打ち合わせに来た、とお伝えください）
  - [google map](https://goo.gl/maps/rYnp92vQz7n)

# TODO

- [x] 念のためUSBマイクも持っていく
- [x] 有線マイクをTLPで借りれないか確認
- [x] マイクスタンドをTLPで借りれないか確認
- [x] せっかくなので機材の写真を撮っておこう

# 話すことのお題目まとめ

話したいことはとりあえずこのissueコメントに書いてもらって前日までにまとめておきます。

## 前半

- iOSDC OPを眺めて気分を上げる
- iOSDC 2016のおおざっぱな来場者数などの数字について
- 練馬にした理由
- トーク選定のやり方
- トーク選定の感想
- スピーカーからの意見
   - スピーカーTシャツがあざやかな緑過ぎて外で着づらい件
- 参加者からの意見について
  - passmarketがyahooメール必要と勘違いさせて新規にYahooメールを取得した参加者が連絡を見落とした件
  - アバター画像のサイズ制限についての意見どうでした？
- 個人的に気になった発表についてありますか？

## 後半

- 次回の開催予定都市の案
- LTも投票できるようにしてしまうと、LTが投票の時間稼ぎだったっぽいのでややこしそうな件
- 参加者からの意見で次に取り入れたいもの
  - Keep 
   - Problem
- その他次回のiOSDCでやりたいこと
  - T

**Comment by hasegawa-tomoki** [comment]
:+1: 

ZOOM H5と、マイク、3mのケーブルを持っていきます。
SDカードに録音できるので、終わったらその場でファイルお渡しすればいいかな。
マルチトラック録音したことないのですが、これ、それぞれの音が入ったファイルが2つできたら困りますか？
（困るなら事前に実験しておきます。「そんなの余裕で統合できる」だったら大丈夫かと。）

あとは、みんなが聞きたいかもしれない内容としては…

* トーク選定はどうやったの？
* 何故練馬？他にもっとあるんじゃないの？

あたりでしょうか。

このタイミングだと次回の話はほとんど出来ないかな、とは思います。

**Comment by hasegawa-tomoki** [comment]
マイクスタンドは1つ卓上のを持ってるけど重いので持っていかないつもりw

**Comment by yimajo** [comment]
@hasegawa-tomoki 録音機材助かります。マルチトラック録音は統合できますよ。では次回の話はナシの方向で考えます。

**Comment by hasegawa-tomoki** [comment]
OK!
次回の話は軽く、ですね。
「妄想ベースで」「やりたいことを」的に！

**Comment by hasegawa-tomoki** [comment]
あ、でも、一応保険で、「いつもの録音機材」もご用意ください！
自分、H5本体のマイクと2本でとったことがないので…！

**Comment by yimajo** [comment]
@hasegawa-tomoki 今日はラジオよろしくお願いします。

**Comment by hasegawa-tomoki** [comment]
向かってまーす！15分くらい前についても大丈夫ですか？

**Comment by yimajo** [comment]
話題追加「スピーカーのTシャツがあざやかな緑過ぎて外で着づらい件」

**Comment by yimajo** [comment]
第2話
https://stargzr.net/radios/2
第3話
https://stargzr.net/radios/3
